import type { CSSProperties } from "react";

/** Co-located styles for the Skills page (list + side preview). */
export const s = {
  page: { display: "flex", flexDirection: "column", minHeight: 0 } satisfies CSSProperties,
  header: {
    display: "flex",
    alignItems: "flex-start",
    gap: 16,
    padding: "22px 32px 14px",
  } satisfies CSSProperties,
  headerText: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  h1: { fontSize: 22, fontWeight: 650, color: "var(--text-primary)", margin: 0 } satisfies CSSProperties,
  subtitle: {
    fontSize: 13,
    color: "var(--text-muted)",
    margin: "4px 0 0",
  } satisfies CSSProperties,
  search: {
    position: "relative",
    display: "flex",
    alignItems: "center",
  } satisfies CSSProperties,
  searchIcon: {
    position: "absolute",
    left: 9,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  searchInput: {
    width: 220,
    padding: "6px 10px 6px 26px",
    borderRadius: 7,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--border)",
    background: "var(--bg-surface)",
    color: "var(--text-primary)",
    fontSize: 13,
    outline: "none",
  } satisfies CSSProperties,

  /** List and preview sit side by side; the preview is the detail pane. */
  body: {
    display: "flex",
    alignItems: "flex-start",
    gap: 16,
    padding: "0 32px 44px",
  } satisfies CSSProperties,
  grid: {
    flex: 1,
    minWidth: 0,
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(280px, 1fr))",
    gap: 12,
  } satisfies CSSProperties,

  card: (selected: boolean): CSSProperties => ({
    display: "flex",
    flexDirection: "column",
    gap: 8,
    padding: 14,
    borderRadius: 10,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: selected ? "var(--accent)" : "var(--border)",
    background: "var(--bg-elevated)",
    cursor: "pointer",
    textAlign: "left",
  }),
  cardHead: { display: "flex", alignItems: "center", gap: 8 } satisfies CSSProperties,
  cardName: {
    flex: 1,
    minWidth: 0,
    fontSize: 14,
    fontWeight: 600,
    color: "var(--text-primary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  cardDescription: {
    fontSize: 12.5,
    lineHeight: 1.45,
    color: "var(--text-secondary)",
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
  } satisfies CSSProperties,
  cardMeta: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    fontSize: 11,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  cardFooter: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    marginTop: 2,
  } satisfies CSSProperties,

  /** Side panel — preview of the selected skill. */
  panel: {
    width: 380,
    flexShrink: 0,
    position: "sticky",
    top: 16,
    maxHeight: "calc(100vh - 120px)",
    overflowY: "auto",
    padding: 16,
    borderRadius: 10,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--border)",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  panelHead: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    marginBottom: 6,
  } satisfies CSSProperties,
  panelTitle: {
    flex: 1,
    minWidth: 0,
    fontSize: 15,
    fontWeight: 650,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  panelDescription: {
    fontSize: 12.5,
    lineHeight: 1.5,
    color: "var(--text-secondary)",
    marginBottom: 12,
  } satisfies CSSProperties,
  panelLabel: {
    fontSize: 10.5,
    fontWeight: 700,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    marginBottom: 6,
  } satisfies CSSProperties,
  panelBody: {
    fontSize: 12,
    lineHeight: 1.5,
    color: "var(--text-secondary)",
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
  } satisfies CSSProperties,
  panelActions: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    marginTop: 14,
  } satisfies CSSProperties,
} as const;
