import type { CSSProperties } from "react";

/** Co-located styles for the skill import modal. */
export const s = {
  wrap: { display: "flex", flexDirection: "column", gap: 14 } satisfies CSSProperties,
  drop: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    padding: "26px 16px",
    borderRadius: 10,
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: "var(--border-strong)",
    background: "var(--bg-surface)",
    cursor: "pointer",
  } satisfies CSSProperties,
  dropTitle: { fontSize: 13.5, fontWeight: 600, color: "var(--text-primary)" } satisfies CSSProperties,
  dropHint: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  note: { fontSize: 12.5, color: "var(--text-muted)" } satisfies CSSProperties,
  error: { fontSize: 12.5, color: "var(--crit)" } satisfies CSSProperties,

  preview: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
    padding: 14,
    borderRadius: 10,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--border)",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  previewHead: { display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" } satisfies CSSProperties,
  previewName: { fontSize: 14.5, fontWeight: 650, color: "var(--text-primary)" } satisfies CSSProperties,
  origin: { fontSize: 11, color: "var(--text-muted)" } satisfies CSSProperties,
  previewDescription: {
    fontSize: 12.5,
    lineHeight: 1.5,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  warnings: {
    margin: 0,
    paddingLeft: 18,
    fontSize: 12,
    lineHeight: 1.6,
    color: "var(--warn)",
  } satisfies CSSProperties,
  ignored: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  ignoredSummary: { cursor: "pointer" } satisfies CSSProperties,
  ignoredList: { margin: "6px 0 0", paddingLeft: 18, lineHeight: 1.6 } satisfies CSSProperties,
  label: {
    fontSize: 10.5,
    fontWeight: 700,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  body: {
    margin: 0,
    maxHeight: 260,
    overflowY: "auto",
    padding: 10,
    borderRadius: 8,
    background: "var(--bg-surface)",
    fontSize: 11.5,
    lineHeight: 1.5,
    color: "var(--text-secondary)",
    whiteSpace: "pre-wrap",
  } satisfies CSSProperties,
} as const;
